package matisse;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;

/**
 *
 * @author Júlia
 */
public class Bloco_de_Notas extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Bloco_de_Notas() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("notas.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNovatela = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        trcFonte = new javax.swing.JComboBox<>();
        aumFont = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPainel = new javax.swing.JTextPane();
        contCaracter = new javax.swing.JLabel();
        checkEstilo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnColor = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mTelanova = new javax.swing.JMenu();
        menNovo = new javax.swing.JMenuItem();
        btnOpen = new javax.swing.JMenuItem();
        menSave = new javax.swing.JMenuItem();
        menSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menMaiusculo = new javax.swing.JMenuItem();
        menMinusculo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bloco de Notas");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(630, 500));
        setSize(new java.awt.Dimension(610, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(610, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(610, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(610, 500));

        btnNovatela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matisse/add.png"))); // NOI18N
        btnNovatela.setText("Novo");
        btnNovatela.setToolTipText("Criar Novo Arquivo");
        btnNovatela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovatelaActionPerformed(evt);
            }
        });

        trcFonte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arial", "Carlito", "Consolas", "Times New Roman", "Dialoginput", "Dubai", "Ebrima", "EngraversGothic BT", "Elephant", "Eras ITC", "Impact", "Webdings", "Yu Gothic" }));
        trcFonte.setToolTipText("Fonte");
        trcFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trcFonteActionPerformed(evt);
            }
        });

        aumFont.setToolTipText("Tamanho da Fonte");
        aumFont.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aumFontStateChanged(evt);
            }
        });

        txtPainel.setMinimumSize(new java.awt.Dimension(630, 500));
        txtPainel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtPainelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtPainel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPainelKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtPainel);

        contCaracter.setText("Caractere: ");

        checkEstilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLAIN", "BOLD", "ITALIC" }));
        checkEstilo.setToolTipText("Estilo");
        checkEstilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEstiloActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matisse/font.png"))); // NOI18N

        btnColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matisse/editor-de-texto.png"))); // NOI18N
        btnColor.setToolTipText("Cor do Texto");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnNovatela)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trcFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(aumFont, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnColor)
                        .addGap(0, 119, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(contCaracter)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnColor)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNovatela)
                                .addComponent(trcFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(aumFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contCaracter)
                .addContainerGap())
        );

        trcFonte.getAccessibleContext().setAccessibleName("fonte");
        aumFont.getAccessibleContext().setAccessibleName("Tamanho da Fonte");
        checkEstilo.getAccessibleContext().setAccessibleName("Estilo");
        btnColor.getAccessibleContext().setAccessibleName("cor do texto");

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        mTelanova.setText("Arquivo");
        mTelanova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTelanovaActionPerformed(evt);
            }
        });

        menNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matisse/add.png"))); // NOI18N
        menNovo.setText("Novo");
        menNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menNovoActionPerformed(evt);
            }
        });
        mTelanova.add(menNovo);

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matisse/folder_explore.png"))); // NOI18N
        btnOpen.setText("Abrir");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        mTelanova.add(btnOpen);

        menSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matisse/page_save.png"))); // NOI18N
        menSave.setText("Salvar");
        menSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSaveActionPerformed(evt);
            }
        });
        mTelanova.add(menSave);

        menSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matisse/cross.png"))); // NOI18N
        menSair.setText("Sair");
        menSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSairActionPerformed(evt);
            }
        });
        mTelanova.add(menSair);

        jMenuBar1.add(mTelanova);

        jMenu2.setText("Editar");

        menMaiusculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matisse/text_uppercase.png"))); // NOI18N
        menMaiusculo.setText("Maiúsculo");
        menMaiusculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menMaiusculoActionPerformed(evt);
            }
        });
        jMenu2.add(menMaiusculo);

        menMinusculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matisse/text_lowercase.png"))); // NOI18N
        menMinusculo.setText("Minúsculo");
        menMinusculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menMinusculoActionPerformed(evt);
            }
        });
        jMenu2.add(menMinusculo);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menSairActionPerformed

    private void mTelanovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTelanovaActionPerformed
        NovaTela();
    }//GEN-LAST:event_mTelanovaActionPerformed

    private void menMaiusculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menMaiusculoActionPerformed
        txtPainel.setText(txtPainel.getText().toUpperCase());
    }//GEN-LAST:event_menMaiusculoActionPerformed

    private void menMinusculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menMinusculoActionPerformed
        txtPainel.setText(txtPainel.getText().toLowerCase());
    }//GEN-LAST:event_menMinusculoActionPerformed

    private void trcFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trcFonteActionPerformed
        tamEfont();
    }//GEN-LAST:event_trcFonteActionPerformed

    private void btnNovatelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovatelaActionPerformed
        NovaTela();
    }//GEN-LAST:event_btnNovatelaActionPerformed

    private void checkEstiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEstiloActionPerformed
        String FontName = trcFonte.getSelectedItem().toString();
        int tamFont = (int) aumFont.getValue();
        
        if (checkEstilo.getSelectedItem().equals("PLAIN")) {
            Font newFont = new Font(FontName, Font.PLAIN, tamFont);
            txtPainel.setFont(newFont);
        }
        if (checkEstilo.getSelectedItem().equals("BOLD")) {
            Font newFont = new Font(FontName, Font.BOLD, tamFont); 
            txtPainel.setFont(newFont);
        }
        if (checkEstilo.getSelectedItem().equals("ITALIC")) {
            Font newFont = new Font(FontName, Font.ITALIC, tamFont);
            txtPainel.setFont(newFont);
        }
    }//GEN-LAST:event_checkEstiloActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        aumFont.setValue(16);
    }//GEN-LAST:event_formWindowOpened

    private void menNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menNovoActionPerformed
        // TODO add your handling code here:
        NovaTela();
    }//GEN-LAST:event_menNovoActionPerformed

    private void menSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSaveActionPerformed
        JFileChooser diretorio = new JFileChooser();
        
        int result = diretorio.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File arq = diretorio.getSelectedFile();
            System.out.println(arq.getPath());
            try {
                OutputStream os = new FileOutputStream(arq);
                OutputStreamWriter writer = new OutputStreamWriter(os);
                BufferedWriter buffer = new BufferedWriter(writer);

                buffer.write(txtPainel.getText());

                buffer.close();
                writer.close();
                os.close();
            } catch (IOException ex) {
                Logger.getLogger(Bloco_de_Notas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menSaveActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        JFileChooser file = new JFileChooser();

        int resposta = file.showOpenDialog(file);
        if (resposta == JFileChooser.APPROVE_OPTION) {
            File arquivo = file.getSelectedFile();
            System.out.println(arquivo.getPath());

            try {
                InputStream is = new FileInputStream(arquivo);
                InputStreamReader in = new InputStreamReader(is);
                BufferedReader buffer = new BufferedReader(in);
                String linha = buffer.readLine();

                while (linha != null) {
                    txtPainel.setText(txtPainel.getText() + linha);
                    linha = buffer.readLine();
                }
                txtPainel.setText(txtPainel.getText());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Bloco_de_Notas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Bloco_de_Notas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void aumFontStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_aumFontStateChanged
        tamEfont();
    }//GEN-LAST:event_aumFontStateChanged

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        JColorChooser cor = new JColorChooser();
        Color cor2 = JColorChooser.showDialog(null, "Cor Fonte", Color.yellow);
        txtPainel.setForeground(cor2);
    }//GEN-LAST:event_btnColorActionPerformed

    private void txtPainelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPainelKeyReleased
        int a = txtPainel.getText().length();
        contCaracter.setText("Caracteres: " + a);
    }//GEN-LAST:event_txtPainelKeyReleased

    private void txtPainelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtPainelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPainelAncestorAdded

    public void NovaTela() {

        Bloco_de_Notas tp = new Bloco_de_Notas();
        tp.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bloco_de_Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bloco_de_Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bloco_de_Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bloco_de_Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bloco_de_Notas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner aumFont;
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnNovatela;
    private javax.swing.JMenuItem btnOpen;
    private javax.swing.JComboBox<String> checkEstilo;
    private javax.swing.JLabel contCaracter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu mTelanova;
    private javax.swing.JMenuItem menMaiusculo;
    private javax.swing.JMenuItem menMinusculo;
    private javax.swing.JMenuItem menNovo;
    private javax.swing.JMenuItem menSair;
    private javax.swing.JMenuItem menSave;
    private javax.swing.JComboBox<String> trcFonte;
    private javax.swing.JTextPane txtPainel;
    // End of variables declaration//GEN-END:variables

    public void tamEfont() {
        String FontName = trcFonte.getSelectedItem().toString();
        int tamFont = (int) aumFont.getValue();
        Font newFont = new Font(FontName, Font.PLAIN, tamFont);
        txtPainel.setFont(newFont);
    }

}
